# Generated by Django 4.2.7 on 2023-11-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=255)),
                ('director', models.TextField(max_length=255)),
                ('lanzamiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Planetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=255)),
                ('clima', models.TextField(max_length=255)),
                ('terreno', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Personajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=255)),
                ('especie', models.TextField(max_length=255)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pelicula', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.peliculas')),
            ],
        ),
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('clasificacion', models.TextField(max_length=100)),
                ('designacion', models.TextField(max_length=255)),
                ('altura_promedio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('esperanza_vida', models.IntegerField()),
                ('idioma', models.TextField(max_length=255)),
                ('personajes', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.personajes')),
            ],
        ),
    ]
