# Generated by Django 4.2.7 on 2023-11-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personajes',
            name='pelicula',
        ),
        migrations.AddField(
            model_name='personajes',
            name='peliculas',
            field=models.ManyToManyField(blank=True, to='api.peliculas'),
        ),
    ]
