# Generated by Django 4.2.7 on 2023-11-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_personajes_pelicula_personajes_peliculas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personajes',
            name='peliculas',
        ),
        migrations.AlterField(
            model_name='personajes',
            name='especie',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
